-- CreateTable
CREATE TABLE "Card" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "value" TEXT NOT NULL,
    "suit" TEXT NOT NULL
);

INSERT INTO "Card" ("id", "value", "suit") VALUES
(1, 'A', 'Copas'),
(2, '2', 'Copas'),
(3, '3', 'Copas'),
(4, '4', 'Copas'),
(5, '5', 'Copas'),
(6, '6', 'Copas'),
(7, '7', 'Copas'),
(8, 'J', 'Copas'),
(9, 'Q', 'Copas'),
(10, 'K', 'Copas'),
(11, 'A', 'Paus'),
(12, '2', 'Paus'),
(13, '3', 'Paus'),
(14, '4', 'Paus'),
(15, '5', 'Paus'),
(16, '6', 'Paus'),
(17, '7', 'Paus'),
(18, 'J', 'Paus'),
(19, 'Q', 'Paus'),
(20, 'K', 'Paus'),
(21, 'A', 'Ouros'),
(22, '2', 'Ouros'),
(23, '3', 'Ouros'),
(24, '4', 'Ouros'),
(25, '5', 'Ouros'),
(26, '6', 'Ouros'),
(27, '7', 'Ouros'),
(28, 'J', 'Ouros'),
(29, 'Q', 'Ouros'),
(30, 'K', 'Ouros'),
(31, 'A', 'Espadas'),
(32, '2', 'Espadas'),
(33, '3', 'Espadas'),
(34, '4', 'Espadas'),
(35, '5', 'Espadas'),
(36, '6', 'Espadas'),
(37, '7', 'Espadas'),
(38, 'J', 'Espadas'),
(39, 'Q', 'Espadas'),
(40, 'K', 'Espadas');
